---
apiVersion: v1
kind: Pod
metadata:
  name: book-frontend
  labels:
    app: web
spec:
  containers:
    - name: book-frontend
      image: robertwilkinsonwork299/reserve-assets-book-frontend
      ports:
        - containerPort: 5176
      env:
      - name: SSL_CERT
        value: /certs/localhost.crt
      - name: SSL_KEY
        value: /certs/localhost.key
      - name: VITE_API_IP
        value: "192.168.49.2"
      - name: VITE_API_PORT
        value: "31000"
      - name: VITE_TYPE
        value: "book"
