---
apiVersion: v1
kind: Pod
metadata:
  name: carpark-frontend
  labels:
    app: web
spec:
  containers:
    - name: carpark-frontend
      image: robertwilkinsonwork299/reserve-assets-carpark-frontend
      ports:
        - containerPort: 5175
      env:
      - name: SSL_CERT
        value: /certs/localhost.crt
      - name: SSL_KEY
        value: /certs/localhost.key
      - name: VITE_API_IP
        value: ""
      - name: VITE_API_PORT
        value: ""
      - name: VITE_TYPE
        value: ""bay""
